import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const router = useRouter();
  const [palettes, setPalettes] = useState([
    {
      name: "Monochrome",
      colors: ["#fff", "#000", "#555"],
    },
    {
      name: "Colorful",
      colors: ["pink", "yellow", "lightgreen", "orangered"],
    },
    {
      name: "Shades of blue",
      colors: ["blue", "darkblue", "teal", "aqua", "lightblue"],
    },
    {
      name: "Monochrome",
      colors: ["#fff", "#000", "#555"],
    },
    {
      name: "Colorful",
      colors: ["pink", "yellow", "lightgreen", "orangered"],
    },
    {
      name: "Shades of blue",
      colors: ["blue", "darkblue", "teal", "aqua", "lightblue"],
    },
  ]);

  useEffect(() => {
    // Wait for session
    setTimeout(() => {
      if (!sessionData) {
        router.push("/login");
      }
    }, 1000);
  });

  return (
    <>
      <Head>
        <title>Palette</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col p-4">
        <h1 className="mb-4 flex flex-wrap text-4xl font-extrabold leading-normal text-gray-700 md:text-[4rem]">
          Wel<span className="mr-6 text-purple-300">come</span>
          {sessionData?.user?.name}
        </h1>
        <div className="your border-gray relative border-2">
          <div className="subtitle absolute left-2 -top-3.5 bg-white px-2">
            Your palettes
          </div>
          <div className="palettes scrollbar-rounded-lg flex gap-6 overflow-auto  p-4 pb-8 scrollbar scrollbar-thumb-gray-200 ">
            {palettes.map((palette, index) => (
              <div
                key={index}
                className="palette cursor-pointer rounded bg-gray-200 p-4 hover:bg-purple-200"
              >
                <div>{palette.name}</div>
                <div className="colors flex gap-2">
                  {palette.colors.map((color, i) => (
                    <div
                      key={i}
                      className="border-1 h-4 w-4 rounded-lg border-black"
                      style={{ backgroundColor: color }}
                    ></div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
